version: '3.8'
services:
  vprodb:
    build:
      context: ./Dockerfile/db
    image: hayzedak/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ DEFAULT USER=guest 
      - RABBITMQ DEFAULT PASS=guest
 
  vproapp:
    build:
      context: ./Dockerfile/app
    image: hayzedak/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
   
  vproweb:
    build:
      context: ./Dockerfile/web
    image: hayzedak/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
        